export { Inicio } from './inicio';
export { Tabla } from './tabla';
export { Calculadora } from './calculadora';
export { Favoritos } from './favoritos';
export { Historial } from './historial';
export { Login } from './login';
export { Registro } from './registro';
export { Acerca } from './acerca';
export { Equipo } from './equipo';